### ISSUE TITLE
Failed to get KEY, ignore.: One or more errors occurred. (The 'data' scheme is not supported.)

### ISSUE THREAD

**Issue by peachyoon** [nilaoda/N_m3u8DL-RE#325]
Hello! 
Ah, I wanted to download a video based on m3u8 from d+, and get "Failed to get KEY" error. Video downloads completely, but doesn't work. Is there a solution to this problem?

m3u8 and key attached
```
https://vod-akc-eu-north-2.media.dssott.com/ps01/disney/3afc8970-e13b-4b65-b94d-fd95efc09365/ctr-all-fdaf0dfb-717e-4ad4-83c6-22d43f137d42-4a4e0435-50a9-4c60-8c6c-60a438687ad3.m3u8
4b7b9cd1e03e42d08515fea1b971f5b5:e3b44feaac3dc8b5461eea1d865c5f51
```

Thank you!

**Comment by fremzuck** [comment]
try to add --custom-hls-key and --custom-hls-iv or try use --mp4-real-time-decryption

**Comment by peachyoon** [comment]
> try to add --custom-hls-key and --custom-hls-iv or try use --mp4-real-time-decryption

II tried, but it doesn't work. The result is as if I'm using wrong key
![Снимок экрана (232)](https://github.com/nilaoda/N_m3u8DL-RE/assets/118711011/df60e69f-3b32-480c-9b03-0aaec73e27fb)

**Comment by Tycoos** [comment]
Hey all,

You won't believe, but I faced the same issue... with exactly the same KID:KEY pair lol @dev-johnny-gh I know it's been more than a year since you reported you solved the issue, but can you help me here? Where to get (and how it looks) the hls key & iv? I went through M3U8 HLS syntax, but the one Disney provided is different... 

Sorry for dumb question, @fremzuck, but how the HLS should look like and where I can get it? In my case in #EXT-X-KEY: I can see PSSH instead of something that might look like HSL key...

**Comment by nilaoda** [comment]
use `--key kid:key`
