### ISSUE TITLE
[Question] Regarding the 10mb extra size of newest version

### ISSUE THREAD

**Issue by knowpwr** [nilaoda/N_m3u8DL-RE#538]
Hello. I have two questions if you do not mind.

1. Why is the new version 10mb larger than the old version (old version is <7mb and new version at 16mb)?
2. How are you able to build an exe that runs on older version of windows when the project targets .net 9.0? I tried building the project and the output exe requires .net 9.0 and cannot run without it. I tried targeting .net 6.0 and I could not compile.
 
Thank you.

**Comment by nilaoda** [comment]
> Why is the new version 10mb larger than the old version (old version is <7mb and new version at 16mb)?

You may have noticed that the executable file for version v0.3.0-beta is larger compared to the previous version. This is due to the removal of UPX compression. While the file size reduction provided by UPX compression can still be valuable in certain scenarios (such as embedded devices or storage-constrained environments), the generally high capacity of modern storage devices and network bandwidth makes its absence less impactful. Removing UPX compression is better suited to optimizing the overall efficiency and compatibility of the development and runtime environments.

---

> How are you able to build an exe that runs on older version of windows when the project targets .net 9.0?

Support for the Windows Vista 32-bit operating system has been achieved using Native AOT compilation and the [YY-Thunks](https://github.com/Chuyu-Team/YY-Thunks) and [VC-LTL](https://github.com/Chuyu-Team/VC-LTL5) libraries.

If you want to manually compile for the old platform, you can check out this code:

https://github.com/nilaoda/N_m3u8DL-RE/blob/4c4617b7804bdd1296951f63224313d64bb680f8/.github/workflows/build_latest.yml#L50-L53

---

The [release note](https://github.com/nilaoda/N_m3u8DL-RE/discussions/539).

**Comment by knowpwr** [comment]
Thank you so much for the information.
